Config = Config or {}
            Config.Redenvelopes  = {
            [1] = {id = 1,type = 1,ownership_type = 1,name = [[ 提升VIP4红包 ]],desc = [[ 恭喜<color@2>{1}</color>提升至<color@1>VIP4</color>，获得<color@1>50绑钻</color>尊享红包 ]],greetings = [[ VIP4尊享红包 ]],trigger_interval = 1,trigger_times = 1,condition = [[ [{vip,4}] ]],money = 50,min_num = 10},
[2] = {id = 2,type = 1,ownership_type = 1,name = [[ 提升VIP5红包 ]],desc = [[ 恭喜<color@2>{1}</color>提升至<color@1>VIP5</color>，获得<color@1>300绑钻</color>尊享红包 ]],greetings = [[ VIP5尊享红包 ]],trigger_interval = 1,trigger_times = 1,condition = [[ [{vip,5}] ]],money = 300,min_num = 10},
[3] = {id = 3,type = 1,ownership_type = 1,name = [[ 提升VIP6红包 ]],desc = [[ 恭喜<color@2>{1}</color>提升至<color@1>VIP6</color>，获得<color@1>500绑钻</color>尊享红包 ]],greetings = [[ VIP6尊享红包 ]],trigger_interval = 1,trigger_times = 1,condition = [[ [{vip,6}] ]],money = 500,min_num = 10},
[4] = {id = 4,type = 1,ownership_type = 1,name = [[ 提升VIP7红包 ]],desc = [[ 恭喜<color@2>{1}</color>提升至<color@1>VIP7</color>，获得<color@1>800绑钻</color>尊享红包 ]],greetings = [[ VIP7尊享红包 ]],trigger_interval = 1,trigger_times = 1,condition = [[ [{vip,7}] ]],money = 800,min_num = 10},
[5] = {id = 5,type = 1,ownership_type = 1,name = [[ 提升VIP8红包 ]],desc = [[ 恭喜<color@2>{1}</color>提升至<color@1>VIP8</color>，获得<color@1>800绑钻</color>尊享红包 ]],greetings = [[ VIP8尊享红包 ]],trigger_interval = 1,trigger_times = 1,condition = [[ [{vip,8}] ]],money = 800,min_num = 10},
[6] = {id = 6,type = 1,ownership_type = 1,name = [[ 提升VIP9红包 ]],desc = [[ 恭喜<color@2>{1}</color>提升至<color@1>VIP9</color>，获得<color@1>800绑钻</color>尊享红包 ]],greetings = [[ VIP9尊享红包 ]],trigger_interval = 1,trigger_times = 1,condition = [[ [{vip,9}] ]],money = 800,min_num = 10},
[7] = {id = 7,type = 1,ownership_type = 1,name = [[ 提升VIP10红包 ]],desc = [[ 恭喜<color@2>{1}</color>提升至<color@1>VIP10</color>，获得<color@1>1000绑钻</color>尊享红包 ]],greetings = [[ VIP10尊享红包 ]],trigger_interval = 1,trigger_times = 1,condition = [[ [{vip,10}] ]],money = 1000,min_num = 10},
[8] = {id = 8,type = 1,ownership_type = 1,name = [[ 提升VIP11红包 ]],desc = [[ 恭喜<color@2>{1}</color>提升至<color@1>VIP11</color>，获得<color@1>1000绑钻</color>尊享红包 ]],greetings = [[ VIP11尊享红包 ]],trigger_interval = 1,trigger_times = 1,condition = [[ [{vip,11}] ]],money = 1000,min_num = 10},
[9] = {id = 9,type = 1,ownership_type = 1,name = [[ 提升VIP12红包 ]],desc = [[ 恭喜<color@2>{1}</color>提升至<color@1>VIP12</color>，获得<color@1>1000绑钻</color>尊享红包 ]],greetings = [[ VIP12尊享红包 ]],trigger_interval = 1,trigger_times = 1,condition = [[ [{vip,12}] ]],money = 1000,min_num = 10},
[11] = {id = 11,type = 2,ownership_type = 1,name = [[ 每日累充红包 ]],desc = [[ <color@2>{1}</color>完成每日累充，获得<color@1>100绑钻</color>尊享红包 ]],greetings = [[ 每日累充红包 ]],trigger_interval = 3,trigger_times = 1,condition = [[ [{today_recharge,300}] ]],money = 100,min_num = 10},
[13] = {id = 13,type = 4,ownership_type = 1,name = [[ 每日首充红包 ]],desc = [[ <color@2>{1}</color>完成每日首充，获得<color@1>50绑钻</color>尊享红包 ]],greetings = [[ 每日首充红包 ]],trigger_interval = 3,trigger_times = 1,condition = [[ [] ]],money = 50,min_num = 10},
[14] = {id = 14,type = 5,ownership_type = 1,name = [[ 月卡投资红包 ]],desc = [[ <color@2>{1}</color>进行月卡投资，获得<color@1>50绑钻</color>尊享红包 ]],greetings = [[ 月卡投资红包 ]],trigger_interval = 3,trigger_times = 1,condition = [[ [] ]],money = 50,min_num = 10},
[15] = {id = 15,type = 6,ownership_type = 1,name = [[ 等级投资红包 ]],desc = [[ <color@2>{1}</color>进行等级投资，获得<color@1>50绑钻</color>尊享红包 ]],greetings = [[ 等级投资红包 ]],trigger_interval = 3,trigger_times = 1,condition = [[ [] ]],money = 50,min_num = 10},
[4203004] = {id = 4203004,type = 99,ownership_type = 1,name = [[ 首领首杀公会红包 ]],desc = [[ <color@2>{1}</color>完成<color@1>全服首杀</color>，获得<color@1>150绑钻</color>尊享红包 ]],greetings = [[ 恭喜您获得首领首杀公会红包 ]],trigger_interval = 0,trigger_times = 0,condition = [[ [] ]],money = 150,min_num = 20},
[42060002] = {id = 42060002,type = 99,ownership_type = 1,name = [[ 符文高塔首杀红包 ]],desc = [[ <color@2>{1}</color>完成<color@1>符文高塔首杀</color>，获得<color@1>50绑钻</color>尊享红包 ]],greetings = [[  ]],trigger_interval = 0,trigger_times = 0,condition = [[ [] ]],money = 50,min_num = 10},
[42060003] = {id = 42060003,type = 99,ownership_type = 1,name = [[ 契灵副本首通红包 ]],desc = [[ <color@2>{1}</color>完成<color@1>契灵副本首通</color>，获得<color@1>50绑钻</color>尊享红包 ]],greetings = [[  ]],trigger_interval = 0,trigger_times = 0,condition = [[ [] ]],money = 50,min_num = 10},
}